name: Test Main

on:
  push:
    branches:
      - main

jobs:
  test-changed-files:
    name: Test Changed Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Detect Changed Files
        run: |
          echo $(git diff --name-only ${{ github.event.before }} ${{ github.event.after }})
          for FILE in $(git diff --name-only ${{ github.event.before }} ${{ github.event.after }}); do 
            if [[ $FILE = ${WATCHED_DIRECTORY}/* ]]; then
              echo "FOUND_WATCHED_FILES=1" >> $GITHUB_ENV
              break
            fi
          done
      
      - name: Found Changed Files
        if: "env.FOUND_WATCHED_FILES"
        run: |
          echo "Files were changed in the ${{ env.WATCHED_DIRECTORY }}! Do the thing!"
      
      - name: No Changed Files
        if: "!env.FOUND_WATCHED_FILES"
        run: |
          echo "No files were changed in the ${{ env.WATCHED_DIRECTORY }}."